### PR TITLE
Patrick

### PR DESCRIPTION
**Pull request by patrick4web**
TextInput need help with Icon not showing up

### CODE REVIEW

**Comment by irvinalcira** [comment]
add resizemode contain to the timage style
and then change the  uri to the image link instead of sourcing from img folder

**Comment by patrick4web** [comment]
Need help with animated View

**Comment by minhkies** [comment]
U can animtaing the width with useEffect with a delay

**Comment by irvinalcira** [comment]
you need to remove everything that isnt necessary like the text and the big view you have.

move the animated.view from the .container view to the .inputcontainer view

change the state of the animated value to 0 instead of 1

**Comment by patrick4web** [comment]
Thanks Irvin it works now

**Pull request merged**
